name: eff-mobile

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      - ./migrations:/app/migrations
  postgres_db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/18/docker
