"""empty message

Revision ID: 7b94e0a6c516
Revises: f6aa6202c16c
Create Date: 2026-02-10 22:26:45.686744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b94e0a6c516'
down_revision: Union[str, Sequence[str], None] = 'f6aa6202c16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_profiles', 'profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('profiles', 'user_profiles')
    # ### end Alembic commands ###
