"""empty message

Revision ID: d191e0eb47db
Revises: 7b94e0a6c516
Create Date: 2026-02-10 22:47:59.410902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd191e0eb47db'
down_revision: Union[str, Sequence[str], None] = '7b94e0a6c516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Отчество (при наличии)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Отчество (при наличии)')
    # ### end Alembic commands ###
