"""empty message

Revision ID: f6aa6202c16c
Revises: e0fbd48b1f0d
Create Date: 2026-02-10 22:23:57.977212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6aa6202c16c'
down_revision: Union[str, Sequence[str], None] = 'e0fbd48b1f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(), server_default='Не указано', nullable=False),
    sa.Column('date_of_birth', sa.String(), server_default='Не указано', nullable=False),
    sa.Column('phone_number', sa.String(), server_default='Не указано', nullable=False),
    sa.Column('bio', sa.TEXT(), server_default='...', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
